### ISSUE TITLE
Also set PATH?

### ISSUE THREAD

**Issue by astoff** [purcell/inheritenv#2]
If one just sets `exec-path` buffer-locally without making a similar change to the `process-environment` PATH entry, then `compile` or `project-compile` won't work as expected after advising them (e.g., giving `env` as the compilation program will show the machine-wide value of PATH). Wouldn't it make sense for `inheritenv-apply` to update PATH in the let-bound value of `process-environment`?

**Comment by purcell** [comment]
I don't think you can ever expect consistently correct results if you set only `exec-path` and leave `process-environment`, because any processes located using `exec-path` would see the mismatched `process-environment`'s `$PATH` and this would generally affect their behaviour, e.g. how they, in turn, locate executables.

Therefore in my view this is a user error and `inheritenv` should not contain any code to work around it.

**Comment by astoff** [comment]
There are pros and cons in setting the PATH, and I'm not actually convinced it should be done.  But if a mismatch between `exec-path` and PATH counts as an _error_, as opposed to a rare but legitimate scenario, then why not fix it?

As a library for package authors, I think the current behavior is fine/better, but for end users a more DWIM approach would be convenient.  I'd rather hide from my config some nonsense `process-environment` manipulation following every single place where `exec-path` is set buffer-locally.

**Comment by purcell** [comment]
What if both `exec-path` and `process-environment` are set and they disagree about `$PATH`? I really feel like it's overstepping things to try to fix this up in `inheritenv`.

**Comment by astoff** [comment]
All right, I take back my suggestion :-)

What I was looking for is something similar to your `envrc` package, but based on dir-local variables rather than a shell script. This is not particularly complicated to do, but it is a bit tricky (just like this package). Especially if you want some major mode hooks to run after the dir/buffer local variables are hacked in.

Since inheritenv is only part of the answer to this matter, it makes sense that it remains focused on just what it does.

> What if both `exec-path` and `process-environment` are set and they disagree about `$PATH`?

Unfortunately this happens even in good packages, for instance the built-in Python mode.
