### ISSUE TITLE
Elpa release?

### ISSUE THREAD

**Issue by leungbk** [purcell/inheritenv#3]
Would it be possible for this package to be part of ELPA? `eglot.el`, which is going to be merged into upstream Emacs, might benefit from this.

**Comment by purcell** [comment]
Ah, interesting news. I don't normally work with ELPA because of the overhead, so I might consider it, but not sure. I think I have access there, and in principle I support the idea, though I prefer there to be a single authoritative source repo, and for this to be it.

**Comment by purcell** [comment]
If `eglot` is going to be in Emacs core, then it would not be enough for `inheritenv` to be in ELPA, would it? It would need to be in the core too.

In any case, I'm surprised that eglot would be merged upstream. Keeping such things as packages is much better for maintenance and backward compatibility IMO. Another option would be to inline the couple of lines of code from `inheritenv` that `eglot` would actually need.

**Comment by astoff** [comment]
I use Eglot with a buffer-local process environment and it doesn't need any patches. (This is by no means not a big achievement, since Eglot doesn't switch buffers before creating a process.)
