### ISSUE TITLE
Where is this behavior specified?

### ISSUE THREAD

**Issue by EugeneNeuron** [purcell/inheritenv#8]
In README you say that this is a specified behavior that temporary buffers do not inherit the calling buffer's environment. Maybe you can remember where it is specified?
I didn't find it in info `(elisp) Current Buffer`.

**Comment by purcell** [comment]
I meant this in the sense that `with-temp-buffer` does nothing to propagate the calling buffer's environment to the new temp buffer, and the fact that `process-environment` is set as a buffer-local in the calling buffer does not automatically cause the variable to be set buffer-locally in the new buffer.

**Comment by EugeneNeuron** [comment]
Thank you, @purcell
